version: '3.8'

services:
  web:
    build: .
    ports: [8000:8000]
    volumes:
      - .:/django
    image: web:django
    env_file:
      - .env
    entrypoint: python
    command: ["manage.py", "runserver", "0.0.0.0:8000"]

volumes:
  app-volumes: