version: '3.8'

services:
  migrator:
    build: .
    env_file:
      - .env
    volumes:
      - app-volumes:/django
    entrypoint: python
    command: ["manage.py", "migrate"]

  web:
    build: .
    ports: [8001:8001]
    volumes:
      - app-volumes:/django
    image: web:django
    env_file:
      - .env
    entrypoint: python
    command: ["manage.py", "runserver", "0.0.0.0:8001"]
    depends_on:
      - migrator

volumes:
  app-volumes: